### PR TITLE
Constitution changes

### PR DESCRIPTION
**Pull request by JJ11teen**
Made some changes, but mainly using this as a forum for opening discussion about others.

### CODE REVIEW

**Comment by JJ11teen** [comment]
Discussion points:

1. Expulsion of a member section is long, could be replaced in favour of a simple board vote.

2. Have not defined how someone can become a member (plus loose language in eligibility)

3. The President subsections should be rewritten to not exclude generality of the parent section

4. The meeting frequency and timing requirements section is a bit of a mess at the moment, I suggest rewriting with a clearer intent.

5. All section references on LaTex should be relative references, in case the numbering or order of sections changes in future.

**Comment by paulpounendis** [comment]
Ok thanks for all this Lucas. I have looked at all the points and agree to them all. I have just merged.

**Comment by JJ11teen** [comment]
Note that the discussion points have not been solved, they are items todo. Individual issues should be created to track them from here.

**Comment by paulpounendis** [comment]
1. The expulsion of the member section is taken straight from the CBS Constitution guideline, so what is written is standard practise, so it's fine. 
2. Fixed. Eligibility has been kept loose by default. If the Board finds anyone violating the rules of the constitution they have the authority to remove membership. 
3. This is fine as the parent section explicitly mentions other rules mentioning the President. It's better to keep such rules in their relevant sections to ensure readers don't have to refer to multiple sections in the document. 
4. These requirements are taken from the CBS Constitution Guideline, as they required by law. 
5. Although I agree, referring to numbered sections explicitly makes it much easier for users in direction. Editors should just take more care.

**Comment by JJ11teen** [comment]
All of these points are **discussion points**. Individual issues should be created to continue the discussion.

1. Standard practise doesn't mean we can improve.
2. Authority to remove membership isn't a reason to loosen eligibility requirements.
3. You may have misinterpreted what I meant. All of the subsubsections restart with 'The President'. This is not in line with other sections where the subject is defined in the parent section:
https://github.com/adelaideblockchain/admin/blob/899780a2cada128583efbfbeb365809ba5a51703/Adelaide-Blockchain-Constitution.tex#L290-L296
4. The legal requirements can be met without the current level of complexity.
5. Latex will convert relative references to numbers for end readers/users when compiled.

**Comment by paulpounendis** [comment]
I have updated discussions into issues. 

3. Aight I get it, will change. 
5. I will work out how to do this.

**Pull request merged**
